name: Debug Kali GUI Port 9020

on:
  workflow_dispatch:

jobs:
  run-kali-cf:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Jalankan Kali Docker (Pakai -dit)
        run: |
          # Perhatikan penambahan -dit di bawah ini agar container tidak langsung exit
          docker run -dit --privileged --name kali-gui -p 9020:8080 -p 9021:5900 iphoneintosh/kali-docker:latest
          
          echo "Menunggu 30 detik agar GUI menyala..."
          sleep 30

      - name: 2. CEK LOG DOCKER
        run: |
          echo "=== STATUS CONTAINER ==="
          docker ps -a
          
          echo -e "\n=== LOG KALI LINUX ==="
          docker logs kali-gui

      - name: 3. Install & Start Cloudflare
        run: |
          wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
          sudo dpkg -i cloudflared-linux-amd64.deb
          
          cloudflared tunnel --url https://127.0.0.1:9020 --no-tls-verify > cloudflared.log 2>&1 &
          
          sleep 10
          
          echo "=========================================================="
          echo "Tautan Cloudflare Tunnel Kamu:"
          grep -o 'https://[-0-9a-z]*\.trycloudflare\.com' cloudflared.log
          echo "=========================================================="
          echo "PENTING: Tambahkan /vnc.html di akhir URL!"
          echo "Password: changeme"
          
          sleep 3600
